version: "3.8"

services:
  bankaccounts-eureka-serker:
    image: 'bankaccounts-eureka-serker'
    container_name: bankaccounts-eureka-serker
    build:
      context: ./eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - bankaccounts-network
  bankaccounts-accounts-service:
    image: 'bankaccounts-accounts-service'
    container_name: bankaccounts-accounts-service
    build:
      context: ./accounts-service
    restart: unless-stopped
    ports:
      - "8091:8091"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://bankaccounts-eureka-serker:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bankaccounts_db
    networks:
      - bankaccounts-network
  bankaccounts-gateway:
    image: 'bankaccounts-gateway'
    container_name: bankaccounts-gateway
    build:
      context: ./bankaccounts-gateway
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://bankaccounts-eureka-serker:8761/eureka
      - KEYLOACK_AUTH_URL=http://keycloak:8080/auth
      - spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/auth/realms/bankaccounts-realm/protocol/openid-connect/token
      - spring.security.oauth2.client.provider.keycloak.authorization-uri=http://keycloak:8080/auth/realms/bankaccounts-realm/protocol/openid-connect/auth
      - spring.security.oauth2.client.provider.keycloak.user-info-uri=http://keycloak:8080/auth/realms/bankaccounts-realm/protocol/openid-connect/userinfo
      - spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://keycloak:8080/auth/realms/bankaccounts-realm/protocol/openid-connect/certs
      - spring.security.oauth2.client.provider.registration.redirect-uri=http://keycloak:8080/login/oauth2/code/keycloak
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/bankaccounts-realm/protocol/openid-connect/certs
    networks:
      - bankaccounts-network
  keycloak:
    image: jboss/keycloak:12.0.3
    container_name: keycloak
    restart: unless-stopped
    command:
      - "-b"
      - "0.0.0.0"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      - bankaccounts-network
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=bankaccounts_db
    ports:
      - 3306:3306
    networks:
      - bankaccounts-network
networks:
  bankaccounts-network:
    driver: bridge